// tools/build-i18n.mjs — generates site/js/i18n.js from tools/i18n-src/<lang>.json.
//
// Each <lang>.json has { ui:{key:text}, commands:{cat:[[id,desc],...]}, faq:[[Q,A],...] }.
// EN is the CANONICAL one (defines the keys/ids/order); the other languages must match.
// Output: window.VOZEN_I18N / VOZEN_COMMANDS / VOZEN_FAQ (the format main-v*.js reads).
//
// Run: node tools/build-i18n.mjs   (then npm run build:site minifies.)

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'tools', 'i18n-src');
// Order = order in the site selector.
const LANGS = ['en', 'pt', 'fr', 'es', 'de', 'tr', 'ar', 'zh', 'ru', 'ko'];

const data = {};
for (const l of LANGS) data[l] = JSON.parse(readFileSync(join(SRC, `${l}.json`), 'utf8'));

const en = data.en;
const uiKeys = Object.keys(en.ui);
const cats = Object.keys(en.commands);

// Validation: each language must have the SAME ui keys, command ids and FAQ count.
for (const l of LANGS) {
  const d = data[l];
  const missing = uiKeys.filter((k) => d.ui[k] == null);
  if (missing.length) throw new Error(`${l}: missing ui keys: ${missing.slice(0, 5).join(', ')}`);
  for (const c of cats) {
    if ((d.commands[c] || []).length !== en.commands[c].length)
      throw new Error(`${l}: command '${c}' has a different item count`);
  }
  if (d.faq.length !== en.faq.length) throw new Error(`${l}: different FAQ item count`);
}

// VOZEN_I18N = { lang: ui }
const I18N = {};
for (const l of LANGS) I18N[l] = data[l].ui;

// VOZEN_COMMANDS = { cat: [[id, {lang:desc}], ...] } — ids/order from EN.
const COMMANDS = {};
for (const c of cats) {
  COMMANDS[c] = en.commands[c].map(([id], i) => {
    const descs = {};
    for (const l of LANGS) descs[l] = data[l].commands[c][i][1];
    return [id, descs];
  });
}

// VOZEN_FAQ = [[{lang:Q}, {lang:A}], ...] — order from EN.
const FAQ = en.faq.map((_, i) => {
  const q = {};
  const a = {};
  for (const l of LANGS) {
    q[l] = data[l].faq[i][0];
    a[l] = data[l].faq[i][1];
  }
  return [q, a];
});

const out =
  `/* Vozen site i18n dictionary. GENERATED by tools/build-i18n.mjs from\n` +
  `   tools/i18n-src/<lang>.json. Do not edit manually; edit the JSON and regenerate.\n` +
  `   Línguas: ${LANGS.join(', ')}. */\n` +
  `window.VOZEN_I18N = ${JSON.stringify(I18N)};\n` +
  `window.VOZEN_COMMANDS = ${JSON.stringify(COMMANDS)};\n` +
  `window.VOZEN_FAQ = ${JSON.stringify(FAQ)};\n`;

writeFileSync(join(ROOT, 'site', 'js', 'i18n-v33.js'), out);
console.log(
  `[build-i18n] ${LANGS.length} línguas · ${uiKeys.length} chaves ui · ${FAQ.length} FAQ -> site/js/i18n-v33.js`,
);
